# Generated by Django 4.2.10 on 2024-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="role",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.CharField(max_length=25),
        ),
    ]
