# Generated by Django 4.2.10 on 2024-03-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_experience_role_alter_projects_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
