# Generated by Django 4.2.10 on 2024-03-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_projects_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="projects", name="url",),
        migrations.AlterField(
            model_name="projects", name="description", field=models.TextField(),
        ),
    ]
