# Generated by Django 4.2.10 on 2024-03-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_projects_url_alter_projects_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="projects", name="image",),
    ]
